FINALALT1/BACKEND

src/main/java/kr/co/moneybridge/core/advice/MyLogAdvice.java
src/main/java/kr/co/moneybridge/core/dummy/DummyEntity.java
src/main/java/kr/co/moneybridge/dto/user/UserRequest.java
src/main/java/kr/co/moneybridge/dto/user/UserResponse.java
src/main/java/kr/co/moneybridge/model/user/User.java

```text
- build 실패발생
-> MyValidAdvice 의 pointcut 경로 수정
-> user 엔티티의 fullname 컬럼 삭제
```

fix: build 실패 에러 수정

---

src/main/resources/application-prod.yml

```text
aws rds 계정 application.yml 추가
```

aws rds 연동

---

scripts/start.sh
scripts/stop.sh

scripts 수정

---

src/main/java/kr/co/moneybridge/model/backoffice/Admin.java
src/main/java/kr/co/moneybridge/model/backoffice/AdminRole.java
src/main/java/kr/co/moneybridge/model/backoffice/AdminStatus.java
src/main/java/kr/co/moneybridge/model/pb/PB.java
src/main/java/kr/co/moneybridge/model/pb/PBRole.java
src/main/java/kr/co/moneybridge/model/pb/PBStatus.java
src/main/java/kr/co/moneybridge/model/reservation/Reservation.java
src/main/java/kr/co/moneybridge/model/reservation/ReservationProcess.java
src/main/java/kr/co/moneybridge/model/reservation/ReservationStatus.java
src/main/java/kr/co/moneybridge/model/reservation/style/Style.java
src/main/java/kr/co/moneybridge/model/reservation/style/StyleStatus.java
src/main/java/kr/co/moneybridge/model/reservation/style/StyleStyle.java
src/main/java/kr/co/moneybridge/model/user/AgreementType.java
src/main/java/kr/co/moneybridge/model/user/User.java
src/main/java/kr/co/moneybridge/model/user/UserAgreement.java
src/main/java/kr/co/moneybridge/model/user/UserInvestInfo.java
src/main/java/kr/co/moneybridge/model/user/UserPropensity.java
src/main/java/kr/co/moneybridge/model/user/UserRole.java
src/main/java/kr/co/moneybridge/model/user/UserStatus.java

- User, PB, Admin, Reservation 모델 생성
- conflict 방지 위해 필요한 클래스지만 담당 아닌 곳은 만들지 않았음.

Env/model: 프로젝트 모델 세팅

---

src/main/java/kr/co/moneybridge/model/backoffice/AdminStatus.java
src/main/java/kr/co/moneybridge/model/backoffice/Answer.java
src/main/java/kr/co/moneybridge/model/backoffice/AnswerRepository.java
src/main/java/kr/co/moneybridge/model/backoffice/FrequentQuestion.java
src/main/java/kr/co/moneybridge/model/backoffice/FrequentQuestionRepository.java
src/main/java/kr/co/moneybridge/model/backoffice/Notice.java
src/main/java/kr/co/moneybridge/model/backoffice/NoticeRepository.java
src/main/java/kr/co/moneybridge/model/backoffice/Question.java
src/main/java/kr/co/moneybridge/model/backoffice/QuestionAuthorRole.java
src/main/java/kr/co/moneybridge/model/backoffice/QuestionRepository.java
src/main/java/kr/co/moneybridge/model/board/Board.java
src/main/java/kr/co/moneybridge/model/board/BoardBookmark.java
src/main/java/kr/co/moneybridge/model/board/BoardBookmarkRepository.java
src/main/java/kr/co/moneybridge/model/board/BoardRepository.java
src/main/java/kr/co/moneybridge/model/board/BoardStatus.java
src/main/java/kr/co/moneybridge/model/board/Reply.java
src/main/java/kr/co/moneybridge/model/board/ReplyRepository.java
src/main/java/kr/co/moneybridge/model/pb/PBBookmark.java
src/main/java/kr/co/moneybridge/model/pb/PBBookmarkRepository.java
src/main/java/kr/co/moneybridge/model/reservation/ReservationStatus.java
src/main/java/kr/co/moneybridge/model/reservation/Review.java
src/main/java/kr/co/moneybridge/model/reservation/ReviewAdherence.java
src/main/java/kr/co/moneybridge/model/reservation/ReviewRepository.java
src/main/java/kr/co/moneybridge/model/reservation/style/StyleStatus.java
src/main/java/kr/co/moneybridge/model/user/UserBookmark.java
src/main/java/kr/co/moneybridge/model/user/UserBookmarkRepository.java

- Review, Board, Reply, UserBookmark, PBBookmark, BoardBookmark, Notice, FrequentQuestion, Question, Answer 모델 생성

Env: model 세팅

---

src/main/java/kr/co/moneybridge/model/pb/Branch.java
src/main/java/kr/co/moneybridge/model/pb/BranchRepository.java
src/main/java/kr/co/moneybridge/model/pb/Career.java
src/main/java/kr/co/moneybridge/model/pb/CareerRepository.java
src/main/java/kr/co/moneybridge/model/pb/Company.java
src/main/java/kr/co/moneybridge/model/pb/CompanyRepository.java
src/main/java/kr/co/moneybridge/model/pb/PB.java
src/main/java/kr/co/moneybridge/model/pb/PBAgreement.java
src/main/java/kr/co/moneybridge/model/pb/PBAgreementRepository.java
src/main/java/kr/co/moneybridge/model/pb/PBPropensity.java
src/main/java/kr/co/moneybridge/model/pb/Portfolio.java
src/main/java/kr/co/moneybridge/model/pb/PortfolioRepository.java
src/main/java/kr/co/moneybridge/model/user/AgreementType.java
src/main/java/kr/co/moneybridge/model/user/UserAgreementRepository.java
src/main/java/kr/co/moneybridge/model/user/UserAgreementType.java
src/main/java/kr/co/moneybridge/model/user/UserInvestInfoRepository.java

UserInvestInfo
UserAgreement
Career
PBAgreement
Branch
Company
Portfolio
모델 class, enum, repository 추가

Env: model 추가

---

src/main/java/kr/co/moneybridge/core/dummy/DataInit.java
src/main/java/kr/co/moneybridge/core/dummy/DummyEntity.java
src/main/java/kr/co/moneybridge/model/board/Board.java
src/main/java/kr/co/moneybridge/model/pb/Portfolio.java
src/main/java/kr/co/moneybridge/model/reservation/Reservation.java
src/main/java/kr/co/moneybridge/model/reservation/ReservationStatus.java
src/main/java/kr/co/moneybridge/model/reservation/Review.java

Env/dummy dummyEntity 추가

---

src/main/java/kr/co/moneybridge/controller/ReservationController.java
src/main/java/kr/co/moneybridge/core/dummy/DummyEntity.java
src/main/java/kr/co/moneybridge/core/util/MyDateUtil.java
src/main/java/kr/co/moneybridge/dto/ResponseDTO.java
src/main/java/kr/co/moneybridge/dto/reservation/ReservationResponse.java
src/main/java/kr/co/moneybridge/model/pb/PB.java
src/main/java/kr/co/moneybridge/service/ReservationService.java
src/main/resources/db/teardown.sql
src/test/java/kr/co/moneybridge/reservation/ReservationControllerTest.java

- PB 상담 예약 사전 정보 조회 기능 구현
- Swagger 코드 추가 필요

Feat: 상담 예약 사전 정보 조회 기능 구현

---

src/main/java/kr/co/moneybridge/core/auth/jwt/MyJwtProvider.java
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application-test.yml
src/test/java/kr/co/moneybridge/controller/UserControllerTest.java

- SECRET_ACCESS와 SECRET_REFRESH 값을 yml에 등록
- @Value로 값 주입
- 서버에는 환경변수 등록해야함

fix: 환경변수 yml에 등록

---

src/main/java/kr/co/moneybridge/controller/ReservationController.java
src/main/java/kr/co/moneybridge/core/advice/MyValidAdvice.java

- PatchMapping도 인식하도록 수정
close #27

Fix: ValidAdvice 수정

---

src/main/java/kr/co/moneybridge/core/dummy/DummyEntity.java
src/main/resources/application-prod.yml

Env : redis 위한 application.yml 세팅

---

src/main/java/kr/co/moneybridge/core/dummy/DummyEntity.java
src/main/java/kr/co/moneybridge/dto/user/UserRequest.java
src/main/resources/application-prod.yml

fix : dummyEntity 수정

---

src/main/java/kr/co/moneybridge/controller/ReservationController.java
src/main/java/kr/co/moneybridge/core/auth/session/MyUserDetailsService.java
src/main/java/kr/co/moneybridge/core/dummy/DummyEntity.java
src/main/java/kr/co/moneybridge/core/util/EnumUtil.java
src/main/java/kr/co/moneybridge/core/util/MyDateUtil.java
src/main/java/kr/co/moneybridge/dto/reservation/ReservationRequest.java
src/main/java/kr/co/moneybridge/dto/reservation/ReservationResponse.java
src/main/java/kr/co/moneybridge/dto/user/UserRequest.java
src/main/java/kr/co/moneybridge/model/reservation/LocationType.java
src/main/java/kr/co/moneybridge/model/reservation/Reservation.java
src/main/java/kr/co/moneybridge/service/ReservationService.java
src/test/java/kr/co/moneybridge/controller/ReservationControllerTest.java

- 상담 예약 신청하기 기능 구현
- 기존 DTO 수정 및 테스트 완료

Feat: 상담 예약 신청하기 기능 구현

---

build.gradle
src/main/java/kr/co/moneybridge/core/dummy/DummyEntity.java
src/main/java/kr/co/moneybridge/dto/user/UserRequest.java
src/main/resources/application-prod.yml

Env: application-prod.yml 변경

---

src/main/java/kr/co/moneybridge/dto/pb/PBRequest.java
src/main/java/kr/co/moneybridge/dto/user/UserRequest.java
src/test/java/kr/co/moneybridge/controller/PBControllerTest.java
src/test/java/kr/co/moneybridge/controller/UserControllerTest.java

- test에서 agreementDTO 생성하는 부분 builder 사용 안하도록 수정
- agreementDTO에서 @builder삭제

Fix: agreementDTO에서 builder삭제

---

build.gradle
src/main/java/kr/co/moneybridge/controller/ReservationController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/core/config/MySwaggerConfig.java
src/main/java/kr/co/moneybridge/core/util/MyEnumUtil.java
src/main/java/kr/co/moneybridge/dto/ResponseDTO.java
src/main/java/kr/co/moneybridge/dto/reservation/ReservationRequest.java
src/main/java/kr/co/moneybridge/dto/reservation/ReservationResponse.java
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application-test.yml

- Swagger 관련 설정 및 적용
- 중첩 DTO 관련 설정 추후 적용 예정
close #21, #23, #48

Feat: Swagger 관련 설정 및 적용

---

src/main/java/kr/co/moneybridge/controller/ReservationController.java
src/main/java/kr/co/moneybridge/core/config/MySecurityConfig.java
src/main/java/kr/co/moneybridge/core/config/MySwaggerConfig.java
src/main/java/kr/co/moneybridge/core/dummy/MockDummyEntity.java
src/main/java/kr/co/moneybridge/dto/reservation/ReservationResponse.java
src/main/java/kr/co/moneybridge/service/ReservationService.java
src/test/java/kr/co/moneybridge/controller/ReservationControllerTest.java
src/test/java/kr/co/moneybridge/controller/ReservationControllerUnitTest.java
src/test/java/kr/co/moneybridge/core/WithMockUser.java
src/test/java/kr/co/moneybridge/core/WithMockUserFactory.java
src/test/java/kr/co/moneybridge/service/ReservationServiceTest.java

- 상담 예약 사전 정보 조회 응답 DTO 수정
- 예약 관련 단위테스트 작성 및 테스트 완료
close #21 
close #23

Fix: 예약 관련 코드 수정 및 단위테스트 추가

---

src/main/java/kr/co/moneybridge/controller/PBController.java
src/main/java/kr/co/moneybridge/controller/UserController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/core/config/MySwaggerConfig.java
src/main/java/kr/co/moneybridge/dto/user/UserRequest.java
src/main/java/kr/co/moneybridge/dto/user/UserResponse.java

swagger 추가
issue #20 
issue #22

Docs: 회원가입, 로그인, 로그아웃, 탈퇴, 토큰 재발급 swagger 추가

---

src/main/java/kr/co/moneybridge/controller/ReservationController.java
src/main/java/kr/co/moneybridge/core/dummy/DummyEntity.java
src/main/java/kr/co/moneybridge/core/dummy/MockDummyEntity.java
src/main/java/kr/co/moneybridge/dto/PageDTO.java
src/main/java/kr/co/moneybridge/dto/reservation/ReservationResponse.java
src/main/java/kr/co/moneybridge/model/pb/Branch.java
src/main/java/kr/co/moneybridge/model/reservation/Review.java
src/main/java/kr/co/moneybridge/model/reservation/ReviewRepository.java
src/main/java/kr/co/moneybridge/model/reservation/StyleRepository.java
src/main/java/kr/co/moneybridge/model/user/UserRepository.java
src/main/java/kr/co/moneybridge/service/ReservationService.java
src/test/java/kr/co/moneybridge/controller/ReservationControllerTest.java
src/test/java/kr/co/moneybridge/model/reservation/ReviewRepositoryTest.java
src/test/java/kr/co/moneybridge/model/user/UserRepositoryTest.java
src/test/java/kr/co/moneybridge/service/ReservationServiceTest.java

- 상담 후기 리스트 조회 코드 수정
- 상담 후기 리스트 조회 Service 단위테스트 작성 및 테스트 완료
- Review.Reservation 연관관계 @OneToOne으로 변경
close #56

Fix: 상담 후기 리스트 조회 코드 수정 

---

src/test/java/kr/co/moneybridge/model/user/UserRepositoryTest.java

Style: 일부 테스트 코드 오타 수정

---

src/main/java/kr/co/moneybridge/controller/UserController.java
src/main/java/kr/co/moneybridge/core/config/MailConfig.java
src/main/java/kr/co/moneybridge/core/dummy/MockDummyEntity.java
src/main/java/kr/co/moneybridge/dto/user/UserResponse.java
src/main/java/kr/co/moneybridge/service/UserService.java
src/test/java/kr/co/moneybridge/controller/UserControllerTest.java
src/test/java/kr/co/moneybridge/controller/UserControllerUnitTest.java
src/test/java/kr/co/moneybridge/service/UserServiceTest.java

로그인시 관리자 계정이면 인증코드 발송
close #22

Feat: 로그인시 관리자 계정이면 인증코드 발송 API + TEST

---

src/main/java/kr/co/moneybridge/controller/ReservationController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/dto/reservation/ReservationResponse.java
src/main/java/kr/co/moneybridge/service/ReservationService.java
src/test/java/kr/co/moneybridge/service/ReservationServiceTest.java

- 고객 관리 페이지 Service 단위테스트 작성 및 테스트 완료

Test: 고객 관리 페이지 Service 단위테스트 작성 및 테스트 완료

---

src/main/java/kr/co/moneybridge/controller/ReservationController.java
src/main/java/kr/co/moneybridge/dto/reservation/ReservationResponse.java
src/main/java/kr/co/moneybridge/model/reservation/ReservationRepository.java
src/main/java/kr/co/moneybridge/model/reservation/ReviewRepository.java
src/main/java/kr/co/moneybridge/service/ReservationService.java
src/test/java/kr/co/moneybridge/model/reservation/ReservationRepositoryTest.java
src/test/java/kr/co/moneybridge/model/reservation/ReviewRepositoryTest.java
src/test/java/kr/co/moneybridge/service/ReservationServiceTest.java

- 고객 관리 페이지 Repository 단위테스트 작성 및 테스트 완료
- 예약 관련 ReviewRepository 단위테스트 작성 및 테스트 완료
- 예약 확인하기 응답 DTO 수정
close #58
close #59 
close #60 
close #61 
close #62 
close #63

Test: 고객 관리 페이지 Repository 단위테스트 작성 및 테스트 완료

---

src/main/java/kr/co/moneybridge/controller/PBController.java
src/main/java/kr/co/moneybridge/controller/UserController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/dto/pb/PBResponse.java
src/main/java/kr/co/moneybridge/dto/user/UserResponse.java
src/main/java/kr/co/moneybridge/model/reservation/ReservationRepository.java
src/main/java/kr/co/moneybridge/model/reservation/ReviewRepository.java
src/main/java/kr/co/moneybridge/service/PBService.java
src/main/java/kr/co/moneybridge/service/UserService.java
src/main/resources/application.yml
src/test/java/kr/co/moneybridge/controller/UserControllerUnitTest.java

- PB 마이페이지 가져오기 API
- 
issue #98

Feat: PB 마이페이지 가져오기 API + Swagger

---

src/main/java/kr/co/moneybridge/model/reservation/ReservationRepository.java
src/main/java/kr/co/moneybridge/service/PBService.java
src/test/java/kr/co/moneybridge/controller/PBControllerTest.java
src/test/java/kr/co/moneybridge/controller/PBControllerUnitTest.java
src/test/java/kr/co/moneybridge/core/WithMockPB.java
src/test/java/kr/co/moneybridge/core/WithMockPBFactory.java
src/test/java/kr/co/moneybridge/core/WithMockUserFactory.java
src/test/java/kr/co/moneybridge/model/reservation/ReviewRepositoryTest.java
src/test/java/kr/co/moneybridge/service/PBServiceTest.java

- PB 마이페이지 가져오기 통합 및 단위 테스트
close #98

Test: PB 마이페이지 가져오기 통합 및 단위 테스트

---

src/main/java/kr/co/moneybridge/controller/UserController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/core/annotation/ValidNumbers.java
src/main/java/kr/co/moneybridge/core/annotation/ValidNumbersValidator.java
src/main/java/kr/co/moneybridge/core/dummy/MockDummyEntity.java
src/main/java/kr/co/moneybridge/dto/user/UserRequest.java
src/main/java/kr/co/moneybridge/model/user/User.java
src/main/java/kr/co/moneybridge/model/user/UserInvestInfo.java
src/main/java/kr/co/moneybridge/model/user/UserInvestInfoRepository.java
src/main/java/kr/co/moneybridge/model/user/UserPropensity.java
src/main/java/kr/co/moneybridge/service/UserService.java
src/test/java/kr/co/moneybridge/controller/UserControllerTest.java
src/test/java/kr/co/moneybridge/controller/UserControllerUnitTest.java
src/test/java/kr/co/moneybridge/model/user/UserInvestInfoTest.java
src/test/java/kr/co/moneybridge/service/UserServiceTest.java

Feat: 투자자 성향 체크 API

---

src/main/java/kr/co/moneybridge/controller/UserController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/core/annotation/ValidNumbersValidator.java
src/main/java/kr/co/moneybridge/core/dummy/DataInit.java
src/main/java/kr/co/moneybridge/core/dummy/DummyEntity.java
src/main/java/kr/co/moneybridge/dto/user/UserRequest.java
src/main/java/kr/co/moneybridge/model/user/UserInvestInfo.java
src/main/java/kr/co/moneybridge/service/UserService.java
src/test/java/kr/co/moneybridge/controller/UserControllerTest.java
src/test/java/kr/co/moneybridge/controller/UserControllerUnitTest.java
src/test/java/kr/co/moneybridge/service/UserServiceTest.java

- 투자자 성향 변경하기 API + Test + Swagger
close #99

Feat: 투자자 성향 변경하기 API + Test + Swagger

---

src/main/java/kr/co/moneybridge/controller/ReservationController.java
src/main/java/kr/co/moneybridge/dto/reservation/ReservationRequest.java
src/main/java/kr/co/moneybridge/dto/reservation/ReservationResponse.java
src/main/java/kr/co/moneybridge/model/user/User.java
src/main/java/kr/co/moneybridge/service/ReservationService.java
src/test/java/kr/co/moneybridge/controller/ReservationControllerTest.java
src/test/java/kr/co/moneybridge/controller/ReservationControllerUnitTest.java

Fix: 예약 관련 코드 및 DTO 수정

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/core/dummy/DataInit.java
src/main/java/kr/co/moneybridge/core/dummy/DummyEntity.java
src/main/java/kr/co/moneybridge/core/dummy/MockDummyEntity.java
src/main/java/kr/co/moneybridge/dto/backOffice/BackOfficeResponse.java
src/main/java/kr/co/moneybridge/model/backoffice/FrequentQuestion.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerTest.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java
src/test/java/kr/co/moneybridge/model/backoffice/FrequentQuestionRepositoryTest.java
src/test/java/kr/co/moneybridge/service/BackOfficeServiceTest.java

Feat: 자주 묻는 질문 목록 가져오기 API + Test + Swagger

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/dto/backOffice/BackOfficeResponse.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/main/resources/application.yml
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerTest.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java
src/test/java/kr/co/moneybridge/model/backoffice/NoticeRepositoryTest.java
src/test/java/kr/co/moneybridge/service/BackOfficeServiceTest.java

Feat: 공지사항 목록 가져오기 API + Test + Swagger

---

src/main/java/kr/co/moneybridge/core/util/MyMemberUtil.java
src/main/java/kr/co/moneybridge/dto/user/UserResponse.java
src/main/java/kr/co/moneybridge/service/UserService.java
src/main/resources/application.yml

- 로그인 성공시 name 추가
- 회원정보 없을 때 null 반환 (이메일 찾기, 비밀번호 찾기)
issue #22 #44

Fix: 회원정보 없을 때 null 반환 및 로그인 성공시 name 추가

---

src/main/java/kr/co/moneybridge/core/util/MyMemberUtil.java
src/main/java/kr/co/moneybridge/dto/user/UserResponse.java
src/main/java/kr/co/moneybridge/service/UserService.java
src/main/resources/application.yml
src/test/java/kr/co/moneybridge/core/util/MyMemberUtilTest.java
src/test/java/kr/co/moneybridge/service/UserServiceTest.java

- test code 수정 - myMemberUtil관련
close #44

Fix: test code 수정 - myMemberUtil관련

---

src/main/java/kr/co/moneybridge/controller/ReservationController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/dto/reservation/ReservationResponse.java
src/main/java/kr/co/moneybridge/service/ReservationService.java
src/main/resources/application.yml
src/test/java/kr/co/moneybridge/controller/ReservationControllerTest.java
src/test/java/kr/co/moneybridge/controller/ReservationControllerUnitTest.java
src/test/java/kr/co/moneybridge/service/ReservationServiceTest.java

- 현재 나의 상담 가능 시간 불러오기 API
close #157

Feat: 현재 나의 상담 가능 시간 불러오기 API + Test + Swagger

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/core/dummy/DummyEntity.java
src/main/java/kr/co/moneybridge/dto/backOffice/BackOfficeResponse.java
src/main/java/kr/co/moneybridge/model/pb/PBRepository.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerTest.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java
src/test/java/kr/co/moneybridge/core/WithMockAdmin.java
src/test/java/kr/co/moneybridge/core/WithMockAdminFactory.java
src/test/java/kr/co/moneybridge/model/pb/PBRepositoryTest.java
src/test/java/kr/co/moneybridge/service/BackOfficeServiceTest.java

- PB 회원 가입 요청 승인 페이지 전체 가져오기 API
issue #160

Feat: PB 회원 가입 요청 승인 페이지 전체 가져오기 API + Test + Swagger

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/core/util/MyMsgUtil.java
src/main/java/kr/co/moneybridge/model/pb/PB.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/main/java/kr/co/moneybridge/service/UserService.java
src/main/resources/application.yml
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerTest.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java
src/test/java/kr/co/moneybridge/service/BackOfficeServiceTest.java
src/test/java/kr/co/moneybridge/service/UserServiceTest.java

- 해당 PB 승인/승인 거부 API
issue #160 
- 승인시 승인 되었다고 이메일 알림
- 승인 거부시 승인 거부 되었다고 이메일 알림 + 데이터 삭제
- 이메일 전송 불가 이메일 주소인 경우, 서버에서 처리 안되고 그냥 반송됨.

Feat: 해당 PB 승인/승인 거부 API + Test + Swagger

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/core/util/MyMsgUtil.java
src/main/java/kr/co/moneybridge/dto/backOffice/BackOfficeResponse.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/main/resources/application.yml
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerTest.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java
src/test/java/kr/co/moneybridge/model/user/UserRepositoryTest.java

- 회원 관리 페이지 전체 가져오기 API
issue #160
- PB는 승인된 PB만 목록에 가져온다. 대기 중인 PB는 리스트에 없음.

Feat: 회원 관리 페이지 전체 가져오기 API + Test + Swagger

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/model/user/User.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/main/resources/application.yml
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerTest.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java
src/test/java/kr/co/moneybridge/service/BackOfficeServiceTest.java

- 해당 투자자를 관리자로 등록/취소 API
issue #160

Feat: 해당 투자자를 관리자로 등록/취소 API

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/core/util/MyMemberUtil.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/main/resources/application.yml
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerTest.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java
src/test/java/kr/co/moneybridge/service/BackOfficeServiceTest.java

- 해당 회원(투자자, PB) 강제 탈퇴 API
issue #160

Feat: 해당 회원(투자자, PB) 강제 탈퇴 API + Test + Swagger

---

src/main/java/kr/co/moneybridge/controller/ReservationController.java
src/main/java/kr/co/moneybridge/dto/reservation/ReservationRequest.java
src/main/java/kr/co/moneybridge/dto/reservation/ReservationResponse.java
src/main/java/kr/co/moneybridge/model/pb/PB.java
src/main/java/kr/co/moneybridge/model/reservation/ReservationRepository.java
src/main/java/kr/co/moneybridge/service/ReservationService.java
src/test/java/kr/co/moneybridge/controller/ReservationControllerUnitTest.java
src/test/java/kr/co/moneybridge/model/reservation/ReservationRepositoryTest.java
src/test/java/kr/co/moneybridge/service/ReservationServiceTest.java

- 월별/일별 예약 정보 조회 기능 구현
- PB 상담 시간 및 메시지 변경하기 기능 구현
- 각각의 기능에 대해 Service 및 Repository 단위테스트 작성 및 테스트 완료
close #153
close #154

Feat: 월별/일별 예약 정보 조회, PB 상담 시간 및 메시지 변경하기 기능 구현

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/dto/backOffice/BackOfficeResponse.java
src/main/java/kr/co/moneybridge/dto/reservation/ReservationResponse.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/main/resources/application.yml

- 상담 현황 페이지 전체 가져오기 API
issue #160

Feat: 상담 현황 페이지 전체 가져오기 API + Swagger

---

src/main/java/kr/co/moneybridge/dto/user/UserRequest.java
src/main/java/kr/co/moneybridge/service/BoardService.java
src/main/java/kr/co/moneybridge/service/PBService.java
src/main/java/kr/co/moneybridge/service/UserService.java
src/main/resources/application-prod.yml
src/main/resources/application-test.yml
src/main/resources/application.yml

- 회원 가입시 기본 profile 사진 추가
issue #20 
- 환경변수에 기본 프로필 이미지 링크 넣어두고
- 서비스 클래스에서 변수 가져와서 이용

Fix: 회원 가입시 기본 profile 사진 추가

---

src/main/java/kr/co/moneybridge/dto/user/UserRequest.java
src/main/java/kr/co/moneybridge/service/BoardService.java
src/main/java/kr/co/moneybridge/service/PBService.java
src/main/java/kr/co/moneybridge/service/UserService.java
src/main/resources/application-prod.yml
src/main/resources/application-test.yml
src/main/resources/application.yml

Fix: prod로 변경

---

src/main/java/kr/co/moneybridge/dto/reservation/ReservationResponse.java
src/main/resources/application.yml
src/test/java/kr/co/moneybridge/controller/ReservationControllerTest.java
src/test/java/kr/co/moneybridge/controller/ReservationControllerUnitTest.java
src/test/java/kr/co/moneybridge/service/ReservationServiceTest.java

Fix: 나의 상담시간 불러오기 - 초 제거

---

src/main/java/kr/co/moneybridge/service/UserService.java
src/main/resources/application.yml
src/test/java/kr/co/moneybridge/service/UserServiceTest.java

- 문제 : 로그인한 id로 예약건수를 조회하는게 아니라 전체 예약건수를 조회하였음
- 해결 : 쿼리 바꿔서 오류 해결

Fix: 나의 예약 페이지 예약건수 오류 해결

---

build.gradle
src/main/java/kr/co/moneybridge/core/util/MyMemberUtil.java
src/main/java/kr/co/moneybridge/core/util/S3Util.java
src/main/java/kr/co/moneybridge/model/pb/PBRepository.java
src/main/java/kr/co/moneybridge/model/pb/PortfolioRepository.java
src/main/java/kr/co/moneybridge/service/PBService.java
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application-test.yml
src/test/java/kr/co/moneybridge/core/util/MyMemberUtilTest.java
src/test/java/kr/co/moneybridge/model/pb/PBRepositoryTest.java

- image resize해서 저장
- s3 버킷명 변경 
- 폴더 단위로 올리기
- 탈퇴시 관련 파일 삭제
issue #20 
- s3버킷명 money-bridge로 변경
- cloudfront도메인 주소도 변경
- 폴더는 default/company/business-card/profile/portfolio/test로 나뉨

Feat: image resize해서 저장, s3 버킷명 변경, 폴더 단위로 올리기, 탈퇴시 관련 파일 삭제

---

hs_err_pid39844.log
hs_err_pid46416.log
src/main/java/kr/co/moneybridge/core/util/S3Util.java
src/main/java/kr/co/moneybridge/dto/backOffice/BackOfficeResponse.java
src/main/java/kr/co/moneybridge/model/reservation/ReservationRepository.java
src/main/resources/application.yml
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerTest.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java
src/test/java/kr/co/moneybridge/controller/PBControllerTest.java
src/test/java/kr/co/moneybridge/controller/UserControllerTest.java
src/test/java/kr/co/moneybridge/controller/UserControllerUnitTest.java
src/test/java/kr/co/moneybridge/model/reservation/ReservationRepositoryTest.java
src/test/java/kr/co/moneybridge/model/reservation/ReviewRepositoryTest.java
src/test/java/kr/co/moneybridge/service/UserServiceTest.java

- 로그인 계정 정보 주는 API
- 투자 성향 테스트 API
- 백오피스 예약건수 +  리스트 API
- PB회원가입 API 통합테스트
close #22 
close #187 
close #160 
issue #20

Test: 테스트 코드 추가

---

src/main/java/kr/co/moneybridge/controller/UserController.java
src/test/java/kr/co/moneybridge/controller/UserControllerUnitTest.java

- httponly; 삭제
- 프론트 테스트용으로 잠시 삭제

Fix: 쿠키 설정 수정

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java
src/test/java/kr/co/moneybridge/service/BackOfficeServiceTest.java

- pagination 수정 - page 파라미터 추가
issue #160 
issue #101

Fix: pagination 수정 - page 파라미터 추가

---

src/main/java/kr/co/moneybridge/controller/UserController.java
src/main/java/kr/co/moneybridge/service/UserService.java
src/main/resources/application.yml

- 리프레시 토큰 헤더에 넣기
- https로 배포하기 전까지 이용
- 쿠키에도 담김

Fix: 리프레시 토큰 헤더에 넣기

---

src/main/resources/application.yml
src/test/java/kr/co/moneybridge/controller/UserControllerTest.java
src/test/java/kr/co/moneybridge/service/UserServiceTest.java

Fix: refresh관련 테스트 임시 주석

---

src/main/java/kr/co/moneybridge/controller/UserController.java
src/main/java/kr/co/moneybridge/service/UserService.java
src/test/java/kr/co/moneybridge/controller/UserControllerTest.java
src/test/java/kr/co/moneybridge/controller/UserControllerUnitTest.java
src/test/java/kr/co/moneybridge/service/UserServiceTest.java

- 리프레시 토큰 쿠키에 sameSite=none과 secure 추가
issue #22

Fix: 리프레시 토큰 쿠키에 sameSite=none과 secure 추가

---

src/test/java/kr/co/moneybridge/model/pb/BranchRepositoryTest.java
src/test/java/kr/co/moneybridge/model/pb/PBAgreementRepositoryTest.java
src/test/java/kr/co/moneybridge/model/pb/PBRepositoryTest.java
src/test/java/kr/co/moneybridge/service/PBServiceTest.java

Test: pb 회원가입 단위 테스트

---

src/main/java/kr/co/moneybridge/FinalProjectBeApplication.java
src/main/java/kr/co/moneybridge/core/scheduler/ReservationScheduler.java
src/main/java/kr/co/moneybridge/model/reservation/ReservationRepository.java
src/test/java/kr/co/moneybridge/model/reservation/ReservationRepositoryTest.java

- 예약 관련 스케쥴러 구현
- 예약 관련 스케쥴러 Repository 단위테스트 작성 및 테스트 완료
close #152

Feat: 예약 관련 스케쥴러 구현

---

src/test/java/kr/co/moneybridge/model/reservation/ReservationRepositoryTest.java

Fix: find_all_peageable_test 수정

---

src/main/java/kr/co/moneybridge/dto/reservation/ReservationResponse.java

Fix: 월별/일별 예약 정보 조회 응답 DTO 수정

---

src/main/java/kr/co/moneybridge/controller/ReservationController.java
src/main/java/kr/co/moneybridge/dto/reservation/ReservationRequest.java
src/main/java/kr/co/moneybridge/service/ReservationService.java

- PB 상담시간 및 메시지 변경하기 요청 DTO 수정

Fix: PB 상담시간 및 메시지 변경하기 요청 DTO 수정

---

src/main/java/kr/co/moneybridge/controller/ReservationController.java
src/main/resources/application-prod.yml

Fix: 상담 예약 신청하기 코드 수정

---

src/main/java/kr/co/moneybridge/service/UserService.java

- 유저 마이페이지 예약 건수 오류 수정
close #98

Fix: 유저 마이페이지 예약 건수 오류 수정

---

src/main/java/kr/co/moneybridge/core/auth/jwt/MyJwtAuthorizationFilter.java

- 인증 또는 권한 필요 없는 URI에서는 토큰 검사 안함.
- MyJwtAuthorizationFilter에서 원래는 토큰값이 없을 때만 토큰 검사를 안하고 넘어갔었는데
인증 또는 권한 검사 필요한 URI에서 문제가 발생할 수 있어 삭제.
- 추가로, 프론트에서 인증 또는 권한 필요없는 URI에도 자동으로 헤더에 토큰을 넣어주기 때문에
해당 경우, 토큰 검사를 안하는 거로 바꿈.

Fix: 인증 또는 권한 필요 없는 URI에서는 토큰 검사 안함

---

src/main/java/kr/co/moneybridge/model/reservation/ReservationRepository.java
src/main/java/kr/co/moneybridge/service/ReservationService.java
src/main/resources/application-prod.yml
src/test/java/kr/co/moneybridge/model/reservation/ReservationRepositoryTest.java
src/test/java/kr/co/moneybridge/service/ReservationServiceTest.java

- prod property에서 AWS RDS의 Timezone을 Asia/Seoul로 변경
- 상담 현황 조회 관련 쿼리 수정

Fix: 상담 현황 조회 관련 쿼리 수정

---

src/main/java/kr/co/moneybridge/core/util/MyDateUtil.java

- MyDateUtil 메서드에 null check 추가

Fix: MyDateUtil 메서드에 null check 추가

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/dto/backOffice/BackOfficeRequest.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java

- 공지사항, FAQ 등록 API + Swagger
issue #213

Feat: 공지사항, FAQ 등록 API + Swagger

---

src/main/java/kr/co/moneybridge/dto/reservation/ReservationRequest.java

Fix: 예약 확정하기 요청 DTO 수정

---

src/main/java/kr/co/moneybridge/dto/pb/PBResponse.java
src/test/java/kr/co/moneybridge/controller/PBControllerTest.java
src/test/java/kr/co/moneybridge/controller/PBControllerUnitTest.java
src/test/java/kr/co/moneybridge/service/PBServiceTest.java

- PB 회원가입 specialty -> speciality 변수명 변경
issue #20

Fix : PB 회원가입 specialty -> speciality 변수명 변경

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/dto/backOffice/BackOfficeResponse.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerTest.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java
src/test/java/kr/co/moneybridge/service/BackOfficeServiceTest.java

- 백오피스 상담 현황 API 분리
issue #160

Fix: 백오피스 상담 현황 API 분리

---

src/main/java/kr/co/moneybridge/controller/ReservationController.java
src/main/java/kr/co/moneybridge/service/ReservationService.java

Fix: 예약 변경시 확정 처리되도록 코드 수정

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/controller/ReservationController.java
src/main/java/kr/co/moneybridge/dto/backOffice/BackOfficeRequest.java
src/main/java/kr/co/moneybridge/model/backoffice/Notice.java
src/main/java/kr/co/moneybridge/model/reservation/ReservationRepository.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java
src/test/java/kr/co/moneybridge/service/BackOfficeServiceTest.java

- 공지사항 수정 및 삭제하기 기능 구현
- 공지사항 수정 및 삭제하기 Controller, Service 단위테스트 작성 및 테스트 완료
- 예약 조회시 취소된 예약은 조회되지 않도록 쿼리 수정

Feat: 공지사항 수정 및 삭제하기 기능 구현

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/dto/backOffice/BackOfficeResponse.java
src/main/java/kr/co/moneybridge/model/pb/PBRepository.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/main/resources/application.yml
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerTest.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java
src/test/java/kr/co/moneybridge/service/BackOfficeServiceTest.java

Fix: backoffice API 수정

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/controller/ReservationController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/dto/backOffice/BackOfficeRequest.java
src/main/java/kr/co/moneybridge/dto/backOffice/BackOfficeResponse.java
src/main/java/kr/co/moneybridge/model/backoffice/FrequentQuestion.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/main/java/kr/co/moneybridge/service/ReservationService.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java
src/test/java/kr/co/moneybridge/service/BackOfficeServiceTest.java
src/test/java/kr/co/moneybridge/service/ReservationServiceTest.java

- FAQ 수정 및 삭제하기 기능 구현
- FAQ 수정 및 삭제하기 Controller, Service 단위테스트 작성 및 테스트 완료

Feat: FAQ 수정 및 삭제하기 기능 구현

---

src/main/java/kr/co/moneybridge/model/reservation/Reservation.java
src/main/java/kr/co/moneybridge/service/ReservationService.java

- 예약 상태 변경시 createdAt도 함께 변경되도록 코드 수정

Fix: 예약 상태 변경시 createdAt도 함께 변경되도록 코드 수정

---

src/main/java/kr/co/moneybridge/controller/UserController.java
src/main/java/kr/co/moneybridge/dto/user/UserRequest.java
src/main/java/kr/co/moneybridge/dto/user/UserResponse.java
src/main/java/kr/co/moneybridge/service/UserService.java
src/test/java/kr/co/moneybridge/controller/UserControllerTest.java
src/test/java/kr/co/moneybridge/controller/UserControllerUnitTest.java
src/test/java/kr/co/moneybridge/service/UserServiceTest.java

- 백오피스 로그인 추가 + 기존 로그인 수정
- 백오피스에서 로그인 할 때만 이메일 인증
issue #22

Feat: 백오피스 로그인 추가 + 기존 로그인 수정

---

src/main/java/kr/co/moneybridge/controller/UserController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/dto/user/UserResponse.java
src/test/java/kr/co/moneybridge/controller/UserControllerTest.java

- 로그인 계정 정보에 isAdmin추가
issue #22

Fix: 로그인 계정 정보에 isAdmin추가

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java
src/test/java/kr/co/moneybridge/service/BackOfficeServiceTest.java

- 공지사항, FAQ 조회 기능 구현, 단위테스트 작성 및 테스트 완료

Feat: 공지사항, FAQ 조회 기능 구현, 단위테스트 작성 및 테스트 완료

---

src/main/java/kr/co/moneybridge/FinalProjectBeApplication.java
src/main/java/kr/co/moneybridge/controller/BackOfficeController.java

- FAQ 목록 조회 API URL 변경
- 서버 실행시 타임존이 Asia/Seoul로 설정되도록 코드 추가

Fix: 서버 실행시 타임존이 Asia/Seoul로 설정되도록 코드 추가

---

src/test/java/kr/co/moneybridge/controller/BackOfficeControllerTest.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java

Fix: 테스트 관련 오류 수정

---

src/main/java/kr/co/moneybridge/controller/ReservationController.java

Fix: 예약 변경하기 유효성 검사 코드 수정

---

src/main/java/kr/co/moneybridge/core/config/MailConfig.java
src/main/java/kr/co/moneybridge/core/util/MyMsgUtil.java
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application-test.yml

- 시스메틱 네이버 계정으로 이메일 주소 변경
- 환경변수 추가 필요
close #43

Feat: 시스메틱 네이버 계정으로 이메일 주소 변경

---

src/main/java/kr/co/moneybridge/dto/reservation/ReservationResponse.java
src/main/java/kr/co/moneybridge/service/ReservationService.java

- 일부 예약 관련 기능에 NULL Check 코드 추가

Fix: 일부 예약 관련 기능에 NULL Check 코드 추가

---

src/main/java/kr/co/moneybridge/core/util/S3Util.java
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application-test.yml
src/test/java/kr/co/moneybridge/service/ReservationServiceTest.java

Fix: cloudfront 제거

---

src/main/resources/application-prod.yml

Fix: RDS 주소 변경

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/core/util/MyMemberUtil.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/main/java/kr/co/moneybridge/service/BoardService.java
src/main/java/kr/co/moneybridge/service/PBService.java
src/main/java/kr/co/moneybridge/service/UserService.java
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application-test.yml

Feat: 지점 삭제 API 추가

---

src/test/java/kr/co/moneybridge/controller/ReservationControllerUnitTest.java

- 예약 관련 Controller 단위테스트 작성 및 테스트 완료

Test: 예약 관련 Controller 단위테스트 작성 및 테스트 완료

---

src/main/java/kr/co/moneybridge/core/util/MyMsgUtil.java

- 이메일 문구 수정 : 회원가입 인증코드입니다 -> 인증코드입니다

Fix: 이메일 문구 수정

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/core/auth/session/MyUserDetailsService.java

- pb 로그인시 이메일에 -가 포함될 때 오류 해결, 백오피스 상담내역, pb승인대기리스트 최신순 정렬

Fix: pb 로그인시 이메일에 -가 포함될 때 오류 해결, 백오피스 상담내역, pb승인대기리스트 최신순 정렬

---

src/test/java/kr/co/moneybridge/controller/BackOfficeControllerTest.java

Fix: Test 코드 수정 - 최신순 정렬

---

src/main/java/kr/co/moneybridge/service/ReservationService.java

- 예약 취소 및 완료 처리를 관리자도 할 수 있도록 코드 수정

Fix: 예약 취소 및 완료 처리를 관리자도 할 수 있도록 코드 수정

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/core/util/GeoCodingUtil.java
src/main/java/kr/co/moneybridge/dto/backOffice/BackOfficeRequest.java
src/main/java/kr/co/moneybridge/model/pb/Branch.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java

Feat: 지점 수정 API 추가

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/controller/PBController.java
src/main/java/kr/co/moneybridge/dto/backOffice/BackOfficeRequest.java
src/main/java/kr/co/moneybridge/dto/pb/PBResponse.java
src/main/java/kr/co/moneybridge/model/pb/Branch.java
src/main/java/kr/co/moneybridge/model/pb/BranchRepository.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/main/java/kr/co/moneybridge/service/PBService.java
src/test/java/kr/co/moneybridge/controller/PBControllerUnitTest.java
src/test/java/kr/co/moneybridge/model/pb/BranchRepositoryTest.java
src/test/java/kr/co/moneybridge/service/PBServiceTest.java

- 지점 검색시 페이지네이션 삭제, 지점 등록 및 수정시 쉼표 추가

Fix: 지점 검색시 페이지네이션 삭제, 지점 등록 및 수정시 쉼표 추가

---

src/main/java/kr/co/moneybridge/core/util/BizMessageUtil.java
src/main/java/kr/co/moneybridge/core/util/MyDateUtil.java
src/main/java/kr/co/moneybridge/core/util/Template.java
src/main/java/kr/co/moneybridge/model/user/UserBookmarkRepository.java
src/main/java/kr/co/moneybridge/service/BoardService.java
src/main/java/kr/co/moneybridge/service/ReservationService.java
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application-test.yml
src/test/java/kr/co/moneybridge/service/BoardServiceTest.java
src/test/java/kr/co/moneybridge/service/ReservationServiceTest.java

- 특정 작업 수행시 카카오 알림톡 발신 기능 구현
close #155

Feat: 특정 작업 수행시 카카오 알림톡 발신 기능 구현

---

src/main/java/kr/co/moneybridge/core/util/BizMessageUtil.java

Fix: 알림톡 관련 액세스 토큰 발급 코드 일부 수정

---

src/main/java/kr/co/moneybridge/core/util/BizMessageUtil.java

Fix: 알림톡 관련 일부 코드 수정

---

src/main/java/kr/co/moneybridge/core/util/BizMessageUtil.java

Style: 오타 수정

---

src/main/java/kr/co/moneybridge/core/util/BizMessageUtil.java

Fix: 알림톡 표시 내용 가공 메서드 추가 및 적용

---

src/main/java/kr/co/moneybridge/core/util/BizMessageUtil.java

Fix: 알림톡 발신 관련 로깅 추가

---

src/main/java/kr/co/moneybridge/core/util/BizMessageUtil.java

Fix: 알림톡 발신 관련 null check 코드 수정

---

src/main/java/kr/co/moneybridge/core/util/BizMessageUtil.java

Fix: 알림톡 발신 관련 메시지 변수 입력 코드 수정

---

src/main/java/kr/co/moneybridge/controller/BoardController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/dto/board/BoardResponse.java
src/main/java/kr/co/moneybridge/model/board/Board.java
src/main/java/kr/co/moneybridge/model/board/BoardRepository.java
src/main/java/kr/co/moneybridge/service/BoardService.java

- PB가 작성한 컨텐츠를 로그인 없이도 조회할 수 있도록 수정
- 컨텐츠 조회시 조회수가 표시되도록 수정
- 메인페이지 맞춤 성향 컨텐츠 조회시 회사명도 같이 표시되도록 수정

Fix: 유지보수 1-1

---

src/main/java/kr/co/moneybridge/core/dummy/DummyEntity.java
src/main/java/kr/co/moneybridge/core/dummy/MockDummyEntity.java

Fix: 유지보수 1-2

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/dto/backOffice/BackOfficeResponse.java
src/main/java/kr/co/moneybridge/model/Member.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerTest.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java

- 상담 삭제하기 기능 구현
- 회원 리스트 조회시 가입일 기준 내림차순으로 조회되도록 수정
- 상담 리스트 조회시 상담 신청일도 표시되도록 수정
- 회원 리스트 조회 관련 테스트 오류 수정

Fix: 유지보수 1-3

---

src/main/java/kr/co/moneybridge/dto/backOffice/BackOfficeResponse.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java

Fix: 유지보수 1-4

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/model/pb/BranchRepository.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java

- 증권사 삭제 쿼리에 @Modifying 추가
- 증권사 수정시 매개변수를 필수로 입력 받지 않도록 수정

Fix: 유지보수 1-6

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java

- 증권사 수정시 UpdateCompanyDTO Null Check 추가

Fix: 유지보수 1-7

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/controller/BoardController.java
src/main/java/kr/co/moneybridge/core/annotation/SwaggerResponses.java
src/main/java/kr/co/moneybridge/dto/board/BoardResponse.java
src/main/java/kr/co/moneybridge/model/pb/PBRepository.java
src/main/java/kr/co/moneybridge/model/user/UserRepository.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/main/java/kr/co/moneybridge/service/BoardService.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java
src/test/java/kr/co/moneybridge/service/BackOfficeServiceTest.java

- 백오피스 투자자 리스트 조회시 검색 기능 추가
- 백오피스 PB 리스트 조회시 검색 기능 추가
- 지점 등록 API 권한을 관리자에서 공통으로 변경
- 이미지 등록 API 추가

Fix: 유지보수 1-8

---

src/main/java/kr/co/moneybridge/service/BoardService.java

- 댓글 및 대댓글 생성일 기준 최신순으로 정렬해서 조회하도록 수정

Fix: 유지보수 1-9

---

src/main/java/kr/co/moneybridge/controller/BackOfficeController.java
src/main/java/kr/co/moneybridge/core/util/BizMessageUtil.java
src/main/java/kr/co/moneybridge/core/util/MemberUtil.java
src/main/java/kr/co/moneybridge/core/util/StibeeUtil.java
src/main/java/kr/co/moneybridge/core/util/Template.java
src/main/java/kr/co/moneybridge/dto/backOffice/BackOfficeRequest.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/main/java/kr/co/moneybridge/service/PBService.java
src/main/java/kr/co/moneybridge/service/ReservationService.java
src/main/java/kr/co/moneybridge/service/UserService.java
src/main/resources/application-prod.yml
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerTest.java
src/test/java/kr/co/moneybridge/controller/BackOfficeControllerUnitTest.java
src/test/java/kr/co/moneybridge/core/util/MemberUtilTest.java
src/test/java/kr/co/moneybridge/service/BackOfficeServiceTest.java
src/test/java/kr/co/moneybridge/service/PBServiceTest.java
src/test/java/kr/co/moneybridge/service/UserServiceTest.java

- 알림톡 템플릿 6, 7, 8 추가
- 예약 취소시 알림톡에 예약 취소일이 담겨서 발송되도록 수정
- 상담 후기 작성시 알림톡이 발송되도록 수정
- 스티비 메일 발송 관련 클래스 추가 및 기존 메일 발송 관련 코드 수정

Fix: 유지보수 1-10

---

src/main/java/kr/co/moneybridge/core/util/MemberUtil.java

- 회원탈퇴시 스티비 주소록 구독이 취소되도록 코드 수정

Fix: 유지보수 1-11

---

src/main/java/kr/co/moneybridge/service/BoardService.java
src/main/java/kr/co/moneybridge/service/PBService.java

- 관리자가 모든 댓글을 삭제할 수 있도록 코드 수정
- PB 리스트 조회시 총 상담 횟수, 상담 후기 갯수가 제대로 출력되도록 코드 수정

Fix: 유지보수 1-12

---

src/main/java/kr/co/moneybridge/service/PBService.java

- PB 리스트 조회시 권한 상관없이 로그인만 했다면 조회되도록 수정

Fix: 유지보수 1-13

---

src/main/java/kr/co/moneybridge/service/PBService.java

Fix: 유지보수 1-14

---

src/main/java/kr/co/moneybridge/model/pb/PBRepository.java
src/main/java/kr/co/moneybridge/service/BackOfficeService.java
src/main/java/kr/co/moneybridge/service/UserService.java

- 로그인시 인증이 실패하면 500번이 아니라 400번 상태코드를 응답하도록 수정
- 지점 삭제시 해당 지점에 소속된 PB가 1명이라도 있다면 삭제하지 못하도록 수정

Fix: 유지보수 1-15

---

src/main/java/kr/co/moneybridge/core/util/BizMessageUtil.java
src/main/java/kr/co/moneybridge/service/BoardService.java

- 신규 컨텐츠 등록시 발신되는 알림톡에서 <figure> 태그 제거
- 신규 컨텐츠 등록시 발신되는 알림톡에 해당 컨텐츠로 이동하는 웹링크 버튼 추가

Fix: 유지보수 1-16

---

src/main/java/kr/co/moneybridge/core/util/BizMessageUtil.java

- 알림톡 발신시 HTML 태그가 제대로 제거되도록 수정

Fix: 유지보수 1-18

---

src/main/java/kr/co/moneybridge/core/util/BizMessageUtil.java

Fix: 유지보수 1-19

---

src/main/java/kr/co/moneybridge/core/util/BizMessageUtil.java

Fix: 유지보수 1-19(2)
